services:
   discovrninja:
     image: guidcruncher/discovrninja:development
     build: .
     container_name: discovrninja
     hostname: discovrninja
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock:ro
     expose:
       - 5000
       - 5001
       - 5053
     stdin_open: true
     tty: true

