#name: discovrninja-dev

services:
  discovrninja-dev:
    user: "${PUID}:${PGID}"
    dns:
      - 192.168.1.201
    build:
      context: .
      dockerfile: Dockerfile-dev
    stdin_open: true
    tty: true
    networks:
      proxy:
    environment:
      - DEBUG_UI=true
      - UID=${PUID}
      - GID=${PGID}
    volumes:
      - .:/home/node/
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/jcrocker/docker/stacks/:/docker/stacks/
    container_name: discovrninja_dev
    hostname: discovrninja-dev
    restart: unless-stopped
    extra_hosts:
      host.docker.internal: 172.17.0.1
      auth.thecrockers.localcert.net: 192.168.1.201
    ports:
      - 5001:5001

networks:
  proxy:
    external: true
