name: discovrninja-dev
 
services:
  discovrninja-dev:
    build:
      context: .
      dockerfile: Dockerfile
#      watch:
#        - action: sync
#          path: ./src/client
#          target: /home/node/app/client
    networks:
      proxy:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/:/home/node/config/
      - ./cache/:/home/node/cache/
      - /home/jcrocker/docker/stacks/:/docker/stacks/:ro
      - ./themes:/home/node/themes
    container_name: discovrninja_dev
    hostname: discovrninja-dev
    restart: unless-stopped
    extra_hosts:
      host.docker.internal: 172.17.0.1
      auth.thecrockers.localcert.net: 192.168.1.201
    ports:
      - 5001:5001

networks:
  proxy:
    external: true
