FROM guidcruncher/node-base:lts-alpine AS base

RUN apk add --no-cache jq git

FROM base AS buildbase

WORKDIR /home/node/

COPY gulpfile.mjs ./
COPY package*.json ./
COPY ./.npm ./
RUN npm i --no-fund --no-audit --prefer-offline  --progress=false  --cache ./.npm

FROM buildbase AS build

WORKDIR /home/node/

COPY . .
RUN npx gulp prebuild js

EXPOSE 5001

ENV THEME_BASE=/home/node/themes
ENV CLIENT_BASE=/home/node/dist/client
ENV CACHE_BASE=/home/node/cache
ENV NODE_CONFIG_DIR=/home/node/config
ENV IN_DOCKER=false
ENV NODE_ENV=development
ENV CADDY_CFG=/home/node/config/caddyfile.d/
ENV DNS_CFG=/home/node/config/dnsmasq.d/
ENV JWT_SECRET="7GYyXKwiM06C1bgTJIg3AwtQjSq9anBU2r-aGXV_sqcA"
ENV IN_DOCKER=true
ENV PACKAGE_VERSION=Development
ENV BUILDDATE=0
ENV STARTDATE=0

RUN gulp dev
ENTRYPOINT ["npx", "nest", "start", "-b", "swc", "-w" ]
