
services:
  discovrninjadev :
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    container_name: discovrninjadev
    hostname: discovrninjadev
    expose:
      - 5001
    ports:
      - 5001:5001
