FROM guidcruncher/node-base:lts-alpine AS base

RUN apk add --no-cache jq git@2.48.1-r0

FROM base AS build

WORKDIR /home/node/

COPY package*.json ./

RUN npm i

COPY . .

RUN npx gulp partials templates js format lint lint-client

EXPOSE 5001

ENV THEME_BASE=/home/node/themes
ENV CLIENT_BASE=/home/node/dist/client
ENV CACHE_BASE=/home/node/cache
ENV NODE_CONFIG_DIR=/home/node/config
ENV IN_DOCKER=false
ENV NODE_ENV=development
ENV CADDY_CFG=/home/node/config/caddyfile.d/
ENV DNS_CFG=/home/node/config/dnsmasq.d/
ENV JWT_SECRET="7GYyXKwiM06C1bgTJIg3AwtQjSq9anBU2r-aGXV_sqcA"
ENV IN_DOCKER=true
ENV PACKAGE_VERSION=Development
ENV BUILDDATE=0
ENV STARTDATE=0

# RUN npx nest start -b swc -w

ENTRYPOINT ["npx", "nest", "start", "-b", "swc", "-w" ]

