services:
   discovrninja:
     image: guidcruncher/discovrninja:development
     build: .
     container_name: discovrninja
     hostname: discovrninja
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock:ro
     networks:
       - proxy
     ports:
       - 5000
       - 5001
       - 5053
     stdin_open: true
     tty: true

networks:
  proxy:
    external: true
